// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGohD_uhnPTp8X3lZ47KsDqwLrF3ucqqw',
    appId: '1:177709034981:web:2614c348dfeb32b10a130c',
    messagingSenderId: '177709034981',
    projectId: 'chfarmguard',
    authDomain: 'chfarmguard.firebaseapp.com',
    storageBucket: 'chfarmguard.firebasestorage.app',
    measurementId: 'G-87B2J7S6YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34rYm3MeWXqkQMimmJpSdSOnbBD8-37U',
    appId: '1:177709034981:android:fce68cf7488f4f2f0a130c',
    messagingSenderId: '177709034981',
    projectId: 'chfarmguard',
    storageBucket: 'chfarmguard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_H8QwRABOpAuYsZDzqvPBIB6ipEM27sY',
    appId: '1:177709034981:ios:0ea0fc4b89e705700a130c',
    messagingSenderId: '177709034981',
    projectId: 'chfarmguard',
    storageBucket: 'chfarmguard.firebasestorage.app',
    iosBundleId: 'com.example.chfarmguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_H8QwRABOpAuYsZDzqvPBIB6ipEM27sY',
    appId: '1:177709034981:ios:0ea0fc4b89e705700a130c',
    messagingSenderId: '177709034981',
    projectId: 'chfarmguard',
    storageBucket: 'chfarmguard.firebasestorage.app',
    iosBundleId: 'com.example.chfarmguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGohD_uhnPTp8X3lZ47KsDqwLrF3ucqqw',
    appId: '1:177709034981:web:035047b1c8ff7a730a130c',
    messagingSenderId: '177709034981',
    projectId: 'chfarmguard',
    authDomain: 'chfarmguard.firebaseapp.com',
    storageBucket: 'chfarmguard.firebasestorage.app',
    measurementId: 'G-MZ6RY2T1JG',
  );
}
